# Generated by Django 4.2.3 on 2023-07-17 07:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_bid_category_comment_listings"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categoryAuction",
                to="auctions.category",
            ),
            preserve_default=False,
        ),
    ]
