# Generated by Django 4.2.3 on 2023-07-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_rename_listings_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
