# Generated by Django 4.2.3 on 2023-07-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_delete_listing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("quantity", models.IntegerField()),
                ("starting_bid", models.IntegerField()),
                ("listing_img", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categoryAuction",
                        to="auctions.category",
                    ),
                ),
            ],
        ),
    ]
