# Generated by Django 4.2.3 on 2023-07-18 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itemm",
                to="auctions.listing",
                unique=True,
            ),
        ),
    ]
