# Generated by Django 4.2.3 on 2023-07-18 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_watchlist_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="item",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="listing",
            field=models.ManyToManyField(to="auctions.listing"),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
