# Generated by Django 4.2.3 on 2023-07-18 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_remove_watchlist_item_watchlist_listing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlistuser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
