# Generated by Django 4.2.3 on 2023-07-19 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_remove_bid_bid_date_bid_bidder_bid_listing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mywatchlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
