# Generated by Django 4.2.3 on 2023-07-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_alter_watchlist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
