# Generated by Django 4.2.3 on 2023-07-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_listing_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="current_bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
