# Generated by Django 4.2.3 on 2023-07-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0018_alter_listing_current_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="listing_img",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
