# Generated by Django 4.2.3 on 2023-07-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0019_alter_listing_listing_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="timestamp",
        ),
    ]
