# Generated by Django 4.2.3 on 2023-07-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0020_remove_comment_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="listing",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="listingwatchlist",
                to="auctions.listing",
            ),
        ),
    ]
